### ISSUE TITLE
"Import from link" broken + other misc issues

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee-v3#63]
### Detailed description of the problem
"Import from link" returns the error `Photo type not supported`, but downloading the photo and uploading it manually works.
### Steps to reproduce the issue
1. Attempt to upload [this photo](https://a.pomf.cat/tsqtac.png) to an album within Lychee, it will finish and then throw an error.
2. Check Logs and observe the error: `2018-10-14 16:13:09 - error - Lychee\Modules\Import::url (64) 	- Photo type not supported (https://a.uguu.se/SLNL5pelwcbm_BlackBullet.png)`
3. Download the photo locally and upload it, observe that it uploads without problems.
### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information
------------------
Lychee Version:  
DB Version:      update_030109
System:          Linux
PHP Version:     7.2
MySQL Version:   50723
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.2.5
Plugins:   
```
### Browser and system
* Browser: Chrome 71.0.3573.0 (Official Build) dev (64-bit)
* Server: Ubuntu 16.04.5 LTS
* Local system: Fedora 28

Additionally, there are a few other misc issues:
* There is an extraneous `$` before the Lychee version on the login prompt
* There is an extraneous `$` in the "Import from link" URL box
* Diagnostics does not report Lychee version, it remains blank

**Comment by ildyria** [comment]
> Additionally, there are a few other misc issues:
>
> - There is an extraneous $ before the Lychee version on the login prompt
> - There is an extraneous $ in the "Import from link" URL box
> - Diagnostics does not report Lychee version, it remains blank

Those are now solved.

Will try to have a look at why import does not work.

**Comment by ildyria** [comment]
I just tried on my test server to import the picture you mentioned, worked perfectly fine.

**Comment by ghost** [comment]
Interesting. I made a fresh clone, new SQL database, new nginx server, etc. for this test and still encountered the issue. Do you have any idea what the cause might be?

**Comment by ildyria** [comment]
Have you tried with an Apache server? (it would be surprising to get a different result but still).

Also, just when opening in my browser, https://a.pomf.cat/tsqtac.png shows me nothing but https://a.uguu.se/SLNL5pelwcbm_BlackBullet.png loads a big picture (multiple MB).

**Comment by ghost** [comment]
I have not tried with Apache; I am not familiar with Apache's syntax. However, I did not notice anything in nginx's error log w/r/t to this issue, so I'm not certain if it's an issue with the web server itself.

**Comment by ildyria** [comment]
quite strange then. :S

**Comment by ghost** [comment]
Closing since it can not be reproduced and thus must be an issue with my particular setup, not Lychee itself. 

Thank you.
